#!/usr/bin/env python3.6

import argparse
import sys

# build the parser
parser = argparse.ArgumentParser(description='Read a file in reverse')
parser.add_argument('filename', help='the file to read')
parser.add_argument('--limit','-l', type=int, help='The number of lines to read')
parser.add_argument('--version','-v', action='version', version='%(prog)s 1.0') 

args = parser.parse_args()

try:
    f = open(args.filename)
    limit = args.limit
except FileNotFoundError as err:
    print(f"Error: {err}")
    sys.exit(1)
else:
# Open the file, read lines and reverse them
    with open(args.filename) as f:
        lines = f.readlines()
        lines.reverse()

        # if limit is not none give just the portion of the lines
        if args.limit:
            lines = lines[:limit]

        # return all the characters in reverse
        for line in lines:
            print(line.strip()[::-1])


