#!/usr/bin/env python3.6

'''
author: Mateusz Maly
github name: matmaly
email: mateuszfmaly@gmail.com
'''

import argparse

parser = argparse.ArgumentParser(description='Seach the chosen language Alphabet for a word user entered')
parser.add_argument('filename',help='File with the words of the language')
parser.add_argument('word', type=str, help='word to be searched')

args = parser.parse_args()

# check whether file with words exists and can be opened
try:
    f = open(args.filename)
except FileNotFoundError as err:
    print(f"Error: {err}")
else:
    with open(args.filename) as f:
        lines = f.readlines()

    for line in lines:
        if line.strip().lower()  == args.word.lower():
            result = f"word: '{args.word}' found in the dictionary"
            break
        else:
            result = f"word: '{args.word}' NOT found in the dictionary"   
    print(result)
