#!/usr/bin/env python3.6
'''
Description: Ask the user for a port number, kill it if it exists, inform the user if it doesn't
Author: Mateusz Maly
Email: mateuszfmaly@gmail.com
github: matmaly
'''

import subprocess
import argparse

parser = argparse.ArgumentParser(description="Process the port number")
parser.add_argument("port", type=int, help="Port number to kill")

args = parser.parse_args()

proc = subprocess.run(["lsof", "-n", f"-i4TCP:{args.port}"], stdout=subprocess.PIPE)

output = str(proc.stdout).split()

for x in range(len(output)):
    print(output[x][1:-4])
    if output[x][1:-4] == "LISTEN":
        print(f"Yes : {output[x]}")

print(args.port)

print(output)
