#!/usr/bin/env python3.6
'''
Description: Ask the user for a port number, kill it if it exists, inform the user if it doesn't
Author: Mateusz Maly
Email: mateuszfmaly@gmail.com
github: matmaly
'''

import subprocess
import argparse


