#!/usr/bin/env python3.6

import random

class Bubble_sort:
    def __init__(self):
        self.list_to_sort = []

    def generate_list(self,val):
        self.list_to_sort = random.sample(range(101), val)
        print(self.list_to_sort)

    def sort_list(self):
        sorted_list = self.list_to_sort
        not_swapped = True
        while not_swapped:
            not_swapped = False
            for index in range(len(sorted_list) -1):
                if sorted_list[index +1] < sorted_list[index]:
                    sorted_list.insert(index, sorted_list[index +1])
                    del sorted_list[index +2]
                    not_swapped = True
        return sorted_list

sortObject = Bubble_sort()

sortObject.generate_list(20)

print(sortObject.sort_list())


